"use client";

import jsPDF from "jspdf";
import { useState } from "react";
import type { BugReport, GenerateBugReportResponse } from "@/lib/types";
import { BugReportResults } from "./BugReportResults";
import { BugReportLoadingSkeleton } from "./BugReportLoadingSkeleton";
import { supabase } from "@/lib/supabase";

export function BugReportForm() {
  const [description, setDescription] = useState("");
  const [report, setReport] = useState<BugReport | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const [company, setCompany] = useState("");
  const [project, setProject] = useState("Bug Report AI");

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setIsLoading(true);
    setReport(null);

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ bugDescription: description }),
      });

      const data = (await response.json()) as
        | GenerateBugReportResponse
        | { error: string };

      if (!response.ok || !("report" in data)) {
        throw new Error("error" in data ? data.error : "Something went wrong.");
      }

      setReport(data.report);

      const user = await supabase.auth.getUser();

      await supabase.from("bug_reports").insert({
        user_id: user.data.user?.id,
        title: data.report.title || "Untitled Bug",
        description: data.report.description || "",
        severity: data.report.severity,
        priority: data.report.priority,

        expected_result: data.report.expectedResult,
        actual_result: data.report.actualResult,
        steps_to_reproduce: data.report.stepsToReproduce,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setIsLoading(false);
    }
  }

  // 📄 PDF EXPORT (FIXED + PROFESSIONAL)
  function downloadPDF() {
    if (!report) return;

    const doc = new jsPDF();
    const date = new Date();

    const formattedDate = date.toLocaleDateString();
    const formattedTime = date.toLocaleTimeString();

    let y = 15;

    // HEADER
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("BUG REPORT SHEET", 105, y, { align: "center" });

    y += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    doc.text(`Company: ${company || "N/A"}`, 10, y);
    doc.text(`Project: ${project}`, 10, y + 6);
    doc.text(`Generated By: AI Bug Reporter`, 10, y + 12);
    doc.text(`Date: ${formattedDate} | Time: ${formattedTime}`, 10, y + 18);

    y += 30;

    // ROW FUNCTION
    const addRow = (label: string, value: string) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      doc.setFillColor(245, 245, 245);
      doc.rect(10, y - 5, 190, 10, "F");

      doc.setFont("helvetica", "bold");
      doc.text(label, 12, y);

      doc.setFont("helvetica", "normal");
      doc.text(value.substring(0, 120), 60, y);

      y += 10;
    };

    addRow("Title:", report.title);
    addRow("Severity:", report.severity);
    addRow("Priority:", report.priority);

    y += 5;

    // DESCRIPTION (FIXED WRAPPING)
    doc.setFont("helvetica", "bold");
    doc.text("Description:", 10, y);
    y += 6;

    doc.setFont("helvetica", "normal");

    const desc = doc.splitTextToSize(report.description, 180);
    doc.text(desc, 10, y);
    y += desc.length * 5 + 10;

    // STEPS
    doc.setFont("helvetica", "bold");
    doc.text("Steps to Reproduce:", 10, y);
    y += 6;

    doc.setFont("helvetica", "normal");

    report.stepsToReproduce.forEach((step, i) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      doc.text(`${i + 1}. ${step}`, 12, y);
      y += 6;
    });

    // FOOTER
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      "This report was automatically generated by Bug Report AI System",
      105,
      285,
      { align: "center" }
    );

    const fileName = `${company || "bug"}-${project}-report.pdf`;
    doc.save(fileName);
  }

  // 📋 COPY (PROFESSIONAL FORMAT)
  function copyReport() {
    if (!report) return;

    const formatted = `
Bug Title: ${report.title}
Severity: ${report.severity}
Priority: ${report.priority}

Description:
${report.description}

Steps:
${report.stepsToReproduce.map((s, i) => `${i + 1}. ${s}`).join("\n")}

Expected:
${report.expectedResult}

Actual:
${report.actualResult}
`;

    navigator.clipboard.writeText(formatted);

    setToast("Professional report copied!");
    setTimeout(() => setToast(null), 2000);
  }

  function clearAll() {
    setDescription("");
    setReport(null);
    setError(null);

    setToast("Cleared successfully!");
    setTimeout(() => setToast(null), 2000);
  }

  return (
    <div className="mx-auto w-full max-w-5xl space-y-10">
      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="rounded-2xl border bg-white p-6 shadow-sm sm:p-8">

          {/* Company + Project */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
            <input
              type="text"
              placeholder="Company Name"
              value={company}
              onChange={(e) => setCompany(e.target.value)}
              className="border p-2 rounded-lg"
            />

            <input
              type="text"
              placeholder="Project Name"
              value={project}
              onChange={(e) => setProject(e.target.value)}
              className="border p-2 rounded-lg"
            />
          </div>

          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Example: When I click the Submit button..."
            rows={8}
            className="w-full rounded-xl border p-3"
            disabled={isLoading}
          />

          {/* Buttons */}
          <div className="flex gap-3 mt-4">
            <button type="button" onClick={copyReport} disabled={!report} className="bg-black text-white px-4 py-2 rounded-lg">
              Copy 📋
            </button>

            <button type="button" onClick={clearAll} className="bg-gray-200 px-4 py-2 rounded-lg">
              Clear
            </button>

            <button type="button" onClick={downloadPDF} disabled={!report} className="bg-indigo-600 text-white px-4 py-2 rounded-lg">
              Download PDF 📄
            </button>
          </div>
        </div>

        {/* Submit */}
        <button
          type="submit"
          disabled={isLoading || !description.trim()}
          className="w-full bg-indigo-600 text-white py-3 rounded-xl"
        >
          {isLoading ? "Generating..." : "Generate Bug Report"}
        </button>
      </form>

      {isLoading && <BugReportLoadingSkeleton />}
      {!isLoading && report && <BugReportResults report={report} />}

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-5 right-5 bg-black text-white px-4 py-2 rounded-lg">
          {toast}
        </div>
      )}
    </div>
  );
}