"use client";
import jsPDF from "jspdf";
import { useState } from "react";
import type { BugReport, GenerateBugReportResponse } from "@/lib/types";
import { BugReportResults } from "./BugReportResults";
import { BugReportLoadingSkeleton } from "./BugReportLoadingSkeleton";

export function BugReportForm() {
  const [description, setDescription] = useState("");
  const [report, setReport] = useState<BugReport | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const [company, setCompany] = useState("");
  const [project, setProject] = useState("Bug Report AI");
  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setIsLoading(true);
    setReport(null);

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ bugDescription: description }),
      });

      const data = (await response.json()) as
        | GenerateBugReportResponse
        | { error: string };

      if (!response.ok || !("report" in data)) {
        throw new Error(
          "error" in data ? data.error : "Something went wrong."
        );
      }

      setReport(data.report);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setIsLoading(false);
    }
  }
  function downloadPDF() {
    if (!report) return;
  
    const doc = new jsPDF();
  
    const date = new Date();
    const formattedDate = date.toLocaleDateString();
    const formattedTime = date.toLocaleTimeString();
  
    let y = 15;
  
    // HEADER
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("BUG REPORT SHEET", 105, y, { align: "center" });
  
    y += 10;
  
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
  
    doc.text(`Company: ${company || "N/A"}`, 10, y);
    doc.text(`Project: ${project}`, 10, y + 6);
    doc.text(`Generated By: AI Bug Reporter`, 10, y + 12);
    doc.text(`Date: ${formattedDate} | Time: ${formattedTime}`, 10, y + 18);
  
    y += 30;
  
    // TABLE STYLE BOXES
    const addRow = (label: string, value: string) => {
      doc.setFillColor(245, 245, 245);
      doc.rect(10, y - 5, 190, 10, "F");
  
      doc.setFont("helvetica", "bold");
      doc.text(label, 12, y);
  
      doc.setFont("helvetica", "normal");
      doc.text(value.substring(0, 120), 60, y);
  
      y += 10;
    };
  
    addRow("Title:", report.title);
    addRow("Severity:", report.severity);
    addRow("Priority:", report.priority);
  
    y += 5;
  
    doc.setFont("helvetica", "bold");
    doc.text("Description:", 10, y);
    y += 6;
  
    doc.setFont("helvetica", "normal");
    doc.text(doc.splitTextToSize(report.description, 180), 10, y);
  
    y += 30;
  
    doc.setFont("helvetica", "bold");
    doc.text("Steps to Reproduce:", 10, y);
    y += 6;
  
    doc.setFont("helvetica", "normal");
    report.stepsToReproduce.forEach((step, i) => {
      doc.text(`${i + 1}. ${step}`, 12, y);
      y += 6;
    });
  
    // FOOTER
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      "This report was automatically generated by Bug Report AI System",
      105,
      285,
      { align: "center" }
    );
  
    doc.save("bug-report.xlsx-style.pdf");
  }
  function copyReport() {
    if (!report) return;

    navigator.clipboard.writeText(JSON.stringify(report, null, 2));

    setToast("Report copied to clipboard!");
    setTimeout(() => setToast(null), 2000);
  }

  function clearAll() {
    setDescription("");
    setReport(null);
    setError(null);

    setToast("Cleared successfully!");
    setTimeout(() => setToast(null), 2000);
  }

  return (
    <div className="mx-auto w-full max-w-5xl space-y-10">
      <form onSubmit={handleSubmit} className="space-y-6" aria-busy={isLoading}>
        <div className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-sm sm:p-8">
          <label
            htmlFor="bug-description"
            className="mb-3 block text-sm font-semibold text-slate-700"
          >
            Describe the bug
          </label>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
  <input
    type="text"
    placeholder="Company Name"
    value={company}
    onChange={(e) => setCompany(e.target.value)}
    className="border p-2 rounded-lg"
  />

  <input
    type="text"
    placeholder="Project Name"
    value={project}
    onChange={(e) => setProject(e.target.value)}
    className="border p-2 rounded-lg"
  />
</div>

          <textarea
            id="bug-description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Example: When I click the Submit button on the checkout page..."
            rows={8}
            className="w-full resize-y rounded-xl border border-slate-200 bg-slate-50/50 px-4 py-3 text-base leading-relaxed text-slate-800 placeholder:text-slate-400 transition-colors focus:border-indigo-400 focus:bg-white focus:outline-none focus:ring-4 focus:ring-indigo-100 disabled:cursor-not-allowed disabled:opacity-60"
            disabled={isLoading}
          />

          <p className="mt-2 text-sm text-slate-500">
            Include what you did, what you expected, and what actually happened.
          </p>

          {/* Buttons */}
          <div className="flex gap-3 mt-4">
            <button
              type="button"
              onClick={copyReport}
              disabled={!report}
              className="px-4 py-2 rounded-lg bg-black text-white disabled:opacity-40"
            >
              Copy 📋
            </button>

            <button
              type="button"
              onClick={clearAll}
              className="px-4 py-2 rounded-lg bg-gray-200"
            >
              Clear
            </button>
            <button
  type="button"
  onClick={downloadPDF}
  disabled={!report}
  className="px-4 py-2 rounded-lg bg-indigo-600 text-white disabled:opacity-40"
>
  Download PDF 📄
</button>
          </div>
        </div>

        {error && (
          <div
            role="alert"
            className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"
          >
            {error}
          </div>
        )}

        <button
          type="submit"
          disabled={isLoading || !description.trim()}
          className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-6 py-3.5 text-base font-semibold text-white shadow-lg shadow-indigo-200 transition-all hover:bg-indigo-700 hover:shadow-indigo-300 focus:outline-none focus:ring-4 focus:ring-indigo-200 disabled:cursor-not-allowed disabled:bg-slate-300 disabled:shadow-none sm:w-auto"
        >
          {isLoading ? (
            <>
              <svg
                className="h-5 w-5 animate-spin"
                viewBox="0 0 24 24"
                fill="none"
                aria-hidden
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                />
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                />
              </svg>
              Generating...
            </>
          ) : (
            <>
              <svg
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
                aria-hidden
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M13 10V3L4 14h7v7l9-11h-7z"
                />
              </svg>
              Generate Bug Report
            </>
          )}
        </button>
      </form>

      {isLoading && <BugReportLoadingSkeleton />}
      {!isLoading && report && <BugReportResults report={report} />}

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-5 right-5 bg-black text-white px-4 py-2 rounded-lg shadow-lg">
          {toast}
        </div>
      )}
    </div>
  );
}